### PR TITLE
RSLC-11 As an admin I should be able to see all users in the system

### PR DESCRIPTION
**Pull request by rodriguevara**
#### Board:
* [Ticket #11](https://trello.com/c/TPpMM5G0/7-rslc-11-as-an-admin-i-should-be-able-to-see-all-users-in-the-system)
---
#### preview
image

### CODE REVIEW

**Comment by sebastiancaraballo** [comment]
Please check with @santiagodiaz, but I think the card refers to create a section on the admin for `User`, not `AdminUser`.

**Comment by rodrieiz** [comment]
> Please check with @santiagodiaz, but I think the card refers to create a section on the admin for `User`, not `AdminUser`.

have you read this comment @rodriguevara ??

**Comment by rodriguevara** [comment]
> > Please check with @santiagodiaz, but I think the card refers to create a section on the admin for `User`, not `AdminUser`.
> 
> have you read this comment @rodriguevara ??

Talked about it with @santiagodiaz and agreed what I originally thought, what the ticket asks is already built in the app.

From the ticket "••**Then I should be able to see a list of users registered on the system**"

preview attached to the description

**Comment by rodrieiz** [comment]
> > > Please check with @santiagodiaz, but I think the card refers to create a section on the admin for `User`, not `AdminUser`.
> > 
> > 
> > have you read this comment @rodriguevara ??
> 
> Talked about it with @santiagodiaz and agreed what I originally thought, what the ticket asks is already built in the app.
> 
> From the ticket "••**Then I should be able to see a list of users registered on the system**"
> 
> preview attached to the description

Nice, you’re right ! my doubt was because the subject said `admin_user_path` but its only the admin helper! ✅

**Review by rodrieiz — APPROVED** [review]
very good job!! 🙌🏼👏🏼
I would like to congratulate you for getting here.
I hope you got something positive from the reviews

**Review by enzofab91 — APPROVED** [review]

**Pull request merged**
